# SPDX-FileCopyrightText: Copyright © DUNE Project contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception

install(FILES
  brezzidouglasmarini1simplex3dlocalbasis.hh
  brezzidouglasmarini1simplex3dlocalcoefficients.hh
  brezzidouglasmarini1simplex3dlocalinterpolation.hh
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/dune/localfunctions/brezzidouglasmarini/brezzidouglasmarini1simplex3d)
